### ISSUE TITLE
Setting proxy for outbound connections

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-docker-compose#14]
**Describe the bug**
When using MutationTaster prioritization and outbound connection is required. When using a corporate proxy one can set it in docker compose via "HTTP_PROXY" environment variables in `.env`. However, when the proxy is set is also used in the Variant Detail View and no detail page is displayed with the following error message:
    ![grafik](https://user-images.githubusercontent.com/1949888/166711381-4b7b5d49-3b19-4bba-b6ac-4bee8da9bcda.png)

**To Reproduce**
1. Set `HTTP_PROXY=http://proxy.compa.ny:8080` in `${varfish-docker-compose-root}/.env`
2. Click on'Filter Variants'
3. Click on 'Filter & Display'
4. Expanding a variant results in AJAX Call error

**Expected behavior**
Using prioritization via MutationTaster and also using the Variant Detail page.

**Additional context**
Probably the "NO_PROXY" environment variable could be set to inhibit proxy routing for connections within the docker container.

**Comment by holtgrewe** [comment]
MutationTaster is not integrated any more we can thus close it for now.
