### ISSUE TITLE
hg38 dataset problem with jannovar files

### ISSUE THREAD

**Issue by danidey** [bihealth/varfish-docker-compose#16]
**Describe the bug**
When installing varfish-docker-compose using the hg38 dataset, jannovar looks for the hg19 files which are configured in the docker-compose.yml file. The hg38 dataset has the files with hg38 as prefix instead of hg19.

**To Reproduce**
1. Follow the installation instructions in the [manual](https://varfish-server.readthedocs.io/en/latest/admin_install.html).
2. Download https://file-public.cubi.bihealth.org/transient/varfish/anthenea/varfish-site-data-v1-20210728-grch38.tar.gz instead of hg19 version.
3. When using docker compose up the following error occurs:
```
varfish-docker-compose-2-jannovar-1  | /usr/local/bin/jannovar: line 10: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
varfish-docker-compose-2-jannovar-1  | Options: RestServerOptions{dbPaths=[/data/hg19_ensembl.ser, /data/hg19_refseq.ser, /data/hg19_refseq_curated.ser], host='0.0.0.0', port=80}
varfish-docker-compose-2-jannovar-1  | Loading database
varfish-docker-compose-2-jannovar-1  | Loading /data/hg19_ensembl.ser...
varfish-docker-compose-2-jannovar-1  | INFO Deserializing JannovarData from /data/hg19_ensembl.ser
varfish-docker-compose-2-jannovar-1  | ERROR: Could not deserialize data list: java.io.FileNotFoundException: /data/hg19_ensembl.ser (No such file or directory)
varfish-docker-compose-2-jannovar-1  | de.charite.compbio.jannovar.data.SerializationException: Could not deserialize data list: java.io.FileNotFoundException: /data/hg19_ensembl.ser (No such file or directory)
varfish-docker-compose-2-jannovar-1  |  at de.charite.compbio.jannovar.data.JannovarDataSerializer.load(JannovarDataSerializer.java:173)
varfish-docker-compose-2-jannovar-1  |  at de.charite.compbio.jannovar.cmd.rest_server.RestServerCommand.loadDatabases(RestServerCommand.java:107)
varfish-docker-compose-2-jannovar-1  |  at de.charite.compbio.jannovar.cmd.rest_server.RestServerCommand.run(RestServerCommand.java:58)
varfish-docker-compose-2-jannovar-1  |  at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
```

**Expected behavior**
Having a configurable and documented option to choose between hg19 or hg38 datasets.

**Comment by danidey** [comment]
**Resolution Proposal**
Possible solutions:
1. Extend .env file with genome version (hg19 or hg38). Currently jannovar-cli is the only container not using the environment file. 
2. docker-compose.override.yml file for jannovar with hg38 prefix in file names

From the view of the administrator setting up varfish the preferred solution would be 1, as the variable would only need to be set once for the whole process (so far I am not sure if any other image needs this information). Solution 2 would be the easier and quick option. 

**Affected Components**
varfish-docker-compose and varfish-server/docs_manual (documentation needs to represent found solution)

**Affected Modules/Files**
docker-compose.yml or also env.example

**Comment by holtgrewe** [comment]
jannovar-cli has been replaced by mehari
