### ISSUE TITLE
Reduce file size of site data

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-docker-compose#6]
Currently the site data for varfish requires 500GB. This amount is very large for personal or cloud deployments and might not be necessary to test the correctness of a varfish-version for development purposes.

## Expected Behavior

A development site data version with at maximum 1GB additional data should be available. This would allow for a quick demo of varfish features or usage in integration testing.

## Proposed solution

Currently varfish-site-data provides volume data for different components as a single tar file. These could be separated first.
Afterwards a reduced set of data should be includeable for testing. Potentially this should utilize synthetic data, so that performance benchmarking of individual features (such as changes to query execution) can be easier.

## Alternatives

1. The current alternative is fulfilling the storage requirements.

**Comment by holtgrewe** [comment]
This now possible for the rocksdb databases. In the future, we will be able to drop the background data from the postgres databases.
